name: ESlint
on: push
jobs: 
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
          registry-url: https://registry.npmjs.org/

      - name: Install node modules
        run: npm ci

      - name: Run ESLint
        run: make lint
